tprov:
  profile: test
  description: test profile active

server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine_test?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  messages:
    basename: lang.messages

indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру

    - url: https://www.skillbox.ru
      name: Skillbox

#    - url: https://www.playback.ru
#      name: PlayBack.Ru

webinterface: /admin